#!/usr/bin/env python3
import glob
import json
import sys
import os
import fileinput

def log(s):
    print(s,file=sys.stderr)

seen_eids = set()

for line in fileinput.input():
    line = line.strip()
    event_data = json.loads(line)
    eid = event_data['id']
    if eid not in seen_eids:
        print(line)
        seen_eids.add(eid)
    else:
        log("\tfound a duplicate: {}".format(eid))
