#!/usr/bin/env python3
import glob
import json
import sys
import os
import gzip

def log(s):
    print(s,file=sys.stderr)

event_files = glob.glob("/github-archive/2015/*.json.gz")
log("got {} files".format(len(event_files)))

for i, filename in enumerate(event_files):
    basename = os.path.basename(filename)
    log("working on {} ({}/{})".format(basename, i, len(event_files)))
    event_file = gzip.open(filename, "rt")
    for line in event_file:
        event_data = json.loads(line)
        eid = event_data['id']
        print("{} {}".format(eid,basename))
